# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "mh+62ISAUhL/P6p/yKAk/xu8a/3L8bwbfDyiIXruBoJmLaWSnAfSOY6z8naPrMOmZpJGt3hRBgb1sfywd1UVSQdnTYZPXykhFdPFJjxFX1X9v6SEwOahOE07VsmCjyPb4/2yaRh878idrqsrp11Jbve16jiKIKZgNoQexe/9wPXaLlKzDlJ6gfBtZZnqn0dL6zruCUMtXzO1gCuYJ1zdpzxK3jZ1+6pAnkEwFpcDOWXen4bWsFlwGq79eY2oipaaKmV+oiX0D7gfvl9umud2vBpIGfeRs/zHXdCFaefmpeDBGC1kkhiwTD4lr+ef2bZvlYztEX5m7Qu/0f5F4u2rmQaXbmNz9tVTvgNF4cqKt57AzUbM895DNUeo4xarDo0KhWlAiONZjYzmiWMmoPcdeiFtH7uPT1OPP0MXqH9kKxIqsuo2IpRTdcHOz+iHHnzamApiX/UYznEw3e3LJYoPLoW2sZrhV7dhq220mRQKqlwAe/hMXjhj4VojAagYrw5uCGCSAAU5mu/3v5e5Y2PoBtvp+SIX7m4v+Tb2+k+wlW7pOhGTIZ4LPcD2etEC8m8jct0NB9sNDGWGM0jGuuDe1SwLc2t4iIdpCkdoMy8c04UyrmyNxRkfWtH9PSe7SIyRyrEtVfaPTOCN6TCHQderlm5X2lmn57/Xv4boZDBIB/Q="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
