travis:
  secure:
    BINSTAR_TOKEN: uSxml1qNvJQI5SYrmI282bqiLDftv+eJpgaZvMaazssixLVs7oM7f1vwIp7AihP0AWIZeOf7tusfp2lWjWL2zpA1ZRIWmzwuN8S94dNqpIPSJN048YEIWFo5rxF7vqiW32jF4s7QQBk4muaTeyLurwRGM2nzeboT2Ze1CtRPWAPYU0rHMol3mN3u0slsgTRaSBWTp8q9zWzizLXa0I+li882iaLgI69xacWuGnHM27qwPtnruriLMyAmpgnCko0XFB/JRyIuS5aCKY1FRVl2I4W2yE4ZTkw6f9eedDs71g1MoDXc6P3knqXKC9CW2cpI3mQwTaVCkU0FgF9abEeN3EFo699szDKcFDntK2nM1xg0CM8PxFgAcK85PBbdmyY2LUfa/B2LBvEKyf7+M94UEZPSDwdHMfpjipwCOxSvcteBwfhkx7wt0KdiUuwFmgibJ5WkIvmuSfovukUH58rLht8PIgTmLrGeKmO0SVsrWn5+wixTb4gNULpHfao5w5s5+DjQ44gv+HmIq2sICD3hVUAiZ1sr0IVhG6k4v+n4lP3HccqBVBLLRGTFEXfYZP1nB4fgDWFNJMy1t5f/MgiEyUWHO71PNr1lE6+dl8H1UlSfG004zkflkCsmtTY3Py5UTGkSh8hLF46l/1dT9+a1NTk4Zty6aO5jWKOJ1DVLnM0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
