travis:
  secure:
    BINSTAR_TOKEN: LIr7xo3e+6rZ67U/9uv4bjEtXyj+26r03hRj0nu2/rdcsQca7vltgUk9OZ+FtaN6RkaEP6KA2DWCvPGJejR8Iq5yd4tcxU0+rCc1H+bPpueA8Lsj76BdFu0wrb72d7/D/lTkuUrT3Su5Wv9XQNx2icQ0Ou3jEICrP++Dy2ZCr2WMchHdh7LNUYFZzjUL3seJGg8TgF5Rjw4cLziiGC5Yw6FOPM1gIiUzUwtLh4dhL4k7DjQhM1ViTYM7Os1cXZ5PHraB9zPHI1081LMzUnH8iy+uSgF5kWTq6Vso6P42KcuYQHdi+7KiTFIQSR2jI4oYfxY0fKcyJOo78FiE8q34LRSwKt9TsSDMg1zH+wKDKNlSXbTUW5+gpLt7NndsFOX9RnAwRXUj71uWLQRFc5DmecY8qdlur835WkUa1gf1vkRU4j0PCLfTwBuV5zie2dAsXN98LmTItzcdFi5i8bG22XSitCSXI471CKk/F55uNEJ1FatgqXkEyhrzfpcRTn8U69ESaqJC4kT55g4vJ7eN+s8xXvjcKXzXVuOBBPM33Z3yoFHZ6ZHdtFGxX6g9TDnhOB8trgnkJgy88IhaFq54fzWdCbz/WKjwpC2xA4iOjXfBVMxeo+guqgEIOeqfy+j8MA1z9Y0ZUzdyEZ2AfsG9C14JNvCNNTWGGYYv/p3Fu+U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
