travis:
  secure:
    BINSTAR_TOKEN: fmz5qn9Bfyvv+eO2pXoYVeITy8TZ2SFFhhOeGQdH8z88XDtt1n47cWAwd+cWtLbVnJlnnisMoKQRxPIJMAqKCSPLkowt95HQpMPlU4g+tLwABhjv7s/atCoW/iEJikoQO1mgU+lFwsDCM18xT8kMyrQwebThbcNiliD9bP++sx8+vaKfTdpFF8iM9d9Y7SxtI80HbZlSqMk5VsfxwN64a8Tc1OOFa/QgZCTA/yfhkcpE3v7kYFBaRKJqKlyLh0SHdzeJBw8wqhpcouTdSvLP3d8YCY6u+Wm7WOwPuVUuRtNL10rmAKmZ+N5fe78sWdclj8SJaezjgPENJPBNBPrj9fEd1ACt3v50AbR1sht8dqJBmpHSKAcr80ycwmOaMIvH/0kogRA5/mldBIzpgsbkZXtYAhe8kARJ/Z2vm1soqVBhl0p896eRgNzwwa9oXLv40wkxeDDhF0dZ7MjfqldXafO+mZhLs8dWKUAK8J1vrSKykH5sD040bFMNYpA6VvDCMKHCP/JnJttEvsCinSwdl/JZ0ImBCkH01+DScXAPXT7K99miWfbxJFm0svWku1jopKBzgCRvS4eMlOV2c/3NjmZLTFZe1bSvhUKHOKlii2Y3/Y33I81dQFHTMWlgYvOiTXVbYjtsjCjI4vkFAnO/FidLYh18H0FUvvNY4t0+MAM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
