travis:
  secure:
    BINSTAR_TOKEN: mh+62ISAUhL/P6p/yKAk/xu8a/3L8bwbfDyiIXruBoJmLaWSnAfSOY6z8naPrMOmZpJGt3hRBgb1sfywd1UVSQdnTYZPXykhFdPFJjxFX1X9v6SEwOahOE07VsmCjyPb4/2yaRh878idrqsrp11Jbve16jiKIKZgNoQexe/9wPXaLlKzDlJ6gfBtZZnqn0dL6zruCUMtXzO1gCuYJ1zdpzxK3jZ1+6pAnkEwFpcDOWXen4bWsFlwGq79eY2oipaaKmV+oiX0D7gfvl9umud2vBpIGfeRs/zHXdCFaefmpeDBGC1kkhiwTD4lr+ef2bZvlYztEX5m7Qu/0f5F4u2rmQaXbmNz9tVTvgNF4cqKt57AzUbM895DNUeo4xarDo0KhWlAiONZjYzmiWMmoPcdeiFtH7uPT1OPP0MXqH9kKxIqsuo2IpRTdcHOz+iHHnzamApiX/UYznEw3e3LJYoPLoW2sZrhV7dhq220mRQKqlwAe/hMXjhj4VojAagYrw5uCGCSAAU5mu/3v5e5Y2PoBtvp+SIX7m4v+Tb2+k+wlW7pOhGTIZ4LPcD2etEC8m8jct0NB9sNDGWGM0jGuuDe1SwLc2t4iIdpCkdoMy8c04UyrmyNxRkfWtH9PSe7SIyRyrEtVfaPTOCN6TCHQderlm5X2lmn57/Xv4boZDBIB/Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
