travis:
  secure:
    BINSTAR_TOKEN: jUIJFhn+8ZQgPTWpqREqBxVGQkfQoirn6WDlJhzWaHZNEuLddZfoZQMFS7cv7aXrwI28qBZJtsg3/bNT2qrvqk/JBmZAFyOj6Ss5jEKQ0TYvKX6Pa48SLXMkNnWL7RaMAKIlsDSsgnruqMXTdJMLpIGUqtLCBANlAhAlKYJHnrmq/7AUdbFfRbY5b8h+CKZ0g3lNDTPiTcnMhO9zGeSvbeGLluWVwh1RYtlTNCRcKBxWWPFRNAKC7dLmLprgx3Z9AKDhqrW/IG5q5yqtQ4AMS/mBmkQNqiJk8ycoxde6xodtwG2YVcZdtzwzXTyMVN99stZho873OmSEi5aMGYHFOdTaschWi62inx+nedUnvrGNEZZkosrZHkf1tBboKsNU+EVNlUS2+/v//iDW36Jx5XF1wYzGTamcH0FhA2BBWsz3thDYNnR/DASsByr0boKLJL0g/WrNPAOTEzVW4TvFHtRd74F6VFGIBhrxDWgbgUSoEm0US9MPs8ntOba05gWgwU8/H9XFGvmYVxCMuLlDj8wUfP5wsQCcyXV1yqcq9zV0AFpNnfikLq4uwnrEgVtU2mC3nDI+PdyPB+b/TcP+s9H8Z56uE+X5AHhlWmcuskKTjq40ZGc1tpQgDFIdd+L7/rV6VI0hgiK+o1l5Gz6WI7yRhIMW09RmlE/Zd4Mr8/M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
