travis:
  secure:
    BINSTAR_TOKEN: K39kBI1Lf83dz9iLtv14SnD24+5NDA1+H98Mv0M/PGYmCHO0BBFILa+itarHPLE7mMgDVMDxhuSn2Rjw3qSnFIf3COb5wsmlpiR+szA9E98BzqAPK7lCjW3IgwNE6abnVtfeR31yDZtphbeO3VYExLJBCC1uyFGS2UU4C/SgioGDseSenYmpNEKYlNjK0XLSWwpwfLpFZX2QNlpg8hCqwdqbKYriX6lDIE1PhymO1nOPfZmTVJ4vIEPhHRKL0W21Jx6DLV+3/EH+0+6pJE54vNeJp2YTJIF6cr5Uqf92XaVSjcpU9eVguPaSfIWUGRLs6gg0PuPLgGTNlJT9qkFvWoa8YhBjLVwNkVACDLVZ0zCCHAtHVIpVlZU5BLE9uCha2A3bQViYqj/tZ6+KTN+NhgoQt4NsiHZEYcAYopPY3QHOic4mIf+Edh9lTFWo5YfVQDl2VgTqpYmDQOnaIuMNR7fqYBdm5VYwC4qwoHHN+5XW7e+M0EEIwEeeeoGeet9nS7pnZ8UBovzU0zfDvhUjOF9AJOd9/HjXAFFgRoj7kANaPPp8AL7VPW4BSC4n2ZjXulTtnjqepLlEaxZOMopUMEEOallXQ0PuNcaQGSj4hRiF4LlW2JCmsXr6s7zSBo1e+XlwSY4uEe681gdy6/1Cr3FwlafsGgoQbv87z/DhG4M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
