travis:
  secure:
    BINSTAR_TOKEN: aqGQ+Oc5iSUw1bIlP4pf7HfVRuiw+65IWAVYbKtqUJUEFewvBGL+04BbegHWYybkMyEXCkU9j9gkbtT0NqKtImMn04+/cyd7jCmWSFy05T2yZiobB/do2kMUbkg8G4kSM9Ayz0dCYtjz5q/5qWalMuEsAkmmH5WFaUzRD1DfIaaPfzX423RUQatjexVNhgvCxgFK3ez/kQkD+WxQcfK6/iHM27RNFX0kXmeQQcNR7QiJxc0R8Mcp4LPjcpn3BaMlKFGQkwjI5y+3khIIqfWJNuQCb8FjTpHtsVvUSA5AhaHJiXDjTdszu3B0zpbUseJNY1ibWY7H6dz4SK5Idm018g7Iavy0bORm/slPWPbJjBHj/+tai0tIdmhp1gf2lLl3WXWHHTRg7gh2fDMW2lo93B3xnjFylTKytQRlbCAFAd9VBHsOd8+V0DYaKyGbxinbw8AQBT7UbL2esHjZt0MWjAxawTPKFSTj2HirNU9Jw6ZcDWrEHIaSl3dXCo21wr55MlHeNpXs9zRnb2UKIVQWifU3VIXsaGhVYzNNzSUZI64Lnr0GEDPizLwnIcplWAFx0k6rSxH/sW4zzSWgVJWJguO38RWICSmd+TW5FZ3MOVLQzQt7SzVtiEEax/nMcZBj7Wg3GyY5HX1pRdY4PrW1BkajWYDVmsgbjCErZ2rB/eg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
