travis:
  secure:
    BINSTAR_TOKEN: rIcNSz2F8s9mJpwZjMyooVF38nr2s6JVze8jfMPhusKv9d5Bz8ktcP3duDNgS3JpcTzZGO2nvHMX+IVMrHK/AonZ1vpPBWtCFmTUn9aa0vwX6K3LBSv02IfvNVlelVN+Jq8EYvFFs7gpq5bf1q4VqTKOcXm3z7WMHq5DGXSCSqCgMsFI8rAM61foBcNXbqV/jGIDniI0oQDhI2WQ0s154e0QIwDNT4q8k7+32x24QAfTc1cSXK/TA91dx7a8Cmf+mFGGhwYuCb16XCvTeQPATKmQwbmGw3V2fpXaBebK6w6yYHrrzmUEYKTdD55i8CucJHCfoiRjO2VOOVCz2WWgf3vFn4R5JhoJA+cUoeIeXuisqPRIqv10ITJw7HiHEYOXY88l5Nm4eWgarU5ALy6osmNAwRi6gFXGyYtRPEjU+xJSF1g4AC/TYD+OgSUPeZxCeOpN6u49ddgRTGk3VbPEErCcanYMjxbaQTZzueYZkcCcd2er5kJZTC+hMfWvnHzjYy+HCY5YaOM9x3yCjXpsE0Kv0J/mlxok0OOFf7dxN2CiRCXUYXIIvc4GikILNuaN8K1ZCu6qhODoV18IPa9FAstWJPC1FpW80TdzZfCcerpv7Z0AeWRS8AEx5slQI4ro+Nyy2HK3XwIH5WsxG6375B760EaiWvH62fVQRfsR+do=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
